name: Padavan Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-mipsel-linux-gnu make curl zip git help2man libtool build-essential automake
        
    - name: Clone Padavan source code
      run: |
        git clone https://github.com/你的GitHub用户名/Padavan.git
        cd Padavan/trunk
        ./build_toolchain.sh
        ./clean_sources.sh

    - name: 克隆 SSR 插件
      run: |
        git clone https://github.com/shadowsocksr-backup/shadowsocksr.git Padavan/trunk/user
        
    - name: Build firmware
      run: |
        cd Padavan/trunk
        ./build_firmware_modify RM2100

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: firmware
        path: Padavan/trunk/output/images/*.trx
