name: Build Padavan Firmware

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-mipsel-linux-gnu make curl zip git
        sudo apt-get install -y build-essential
        git clone https://github.com/cucci666/Padavan.git
        cd Padavan/toolchain-mipsel
        ./build_toolchain

    - name: Build firmware
      run: |
        cd Padavan/trunk
        ./build_firmware

    - name: Upload firmware
      uses: actions/upload-artifact@v3
      with:
        name: firmware
        path: Padavan/trunk/output/images/*.trx
