name: Build Padavan with ShadowsocksR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-aarch64-linux-gnu bison flex libssl-dev bc make curl zip help2man libtool gcc-mipsel-linux-gnu binutils-mipsel-linux-gnu

    - name: Clone Padavan source code
      run: |
        git clone https://github.com/cucci666/Padavan.git
        cd Padavan/trunk
        ./build_toolchain.sh
        ./clean_sources.sh

    - name: Clone SSR
      run: |
        cd Padavan/trunk/user
        git clone https://github.com/shadowsocksr-backup/shadowsocksr.git

    - name: Build firmware
      run: |
        cd Padavan/trunk
        ./build_firmware_modify RM2100

    - name: Upload firmware
      uses: actions/upload-artifact@v3
      with:
        name: firmware
        path: Padavan/trunk/output/images/*.trx
